[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.95
blur = true

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
size = 11.0

[font.offset]
x = 0
y = 1

[cursor]
style = "Block"
unfocused_hollow = true

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
